### ISSUE TITLE
A lot of deprecated depencies. Pls update

### ISSUE THREAD

**Issue by gOOvER** [Julius-Ulee/AmeliaBot-Discord#2]
Can you please update the depencies and start using discord.js 14? 13 will be eol in a short time. I never saw such a big row of decrecated modules

```
Installing nodejs packages
npm WARN tarball tarball data for prism-media@https://codeload.github.com/distubejs/prism-media/tar.gz/main#workaround.tar.gz (sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw==) seems to be corrupted. Trying again.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN tarball tarball data for prism-media@https://codeload.github.com/distubejs/prism-media/tar.gz/main#workaround.tar.gz (sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw==) seems to be corrupted. Trying again.
npm WARN deprecated @discordjs/builders@0.9.0: no longer supported
npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm WARN deprecated distube@3.3.4: Update to latest version instead
npm WARN deprecated @ksoft/api@3.1.9: KSoft is no longer active. Take a look at https://ravy.org/api
npm WARN deprecated @discordjs/builders@0.16.0: no longer supported
npm WARN deprecated discord-api-types@0.24.0: No longer supported. Install the latest release!
npm WARN deprecated @distube/youtube-dl@2.2.4: Use '@distube/yt-dlp' instead
npm WARN deprecated @discordjs/collection@0.7.0: no longer supported
npm ERR! code EINTEGRITY
npm ERR! sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw== integrity checksum failed when using sha512: wanted sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw== but got sha512-NgqmmDCFM4cuPFRXBOcU9CYQ2ouYLivZ5OLMuM3lrNnaQ8mIiSfT8IuGqog9Oc1cPQll37l0o4ZJtys5zje9/Q==. (9969 bytes)

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-07-31T09_02_03_131Z-debug-0.log
npm WARN config production Use `--omit=dev` instead.
npm WARN deprecated @distube/youtube-dl@2.2.4: Use '@distube/yt-dlp' instead
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @discordjs/collection@0.7.0: no longer supported
npm WARN deprecated @discordjs/builders@0.9.0: no longer supported
npm WARN tarball tarball data for prism-media@https://codeload.github.com/distubejs/prism-media/tar.gz/main#workaround.tar.gz (sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw==) seems to be corrupted. Trying again.
npm WARN deprecated @discordjs/builders@0.16.0: no longer supported
npm WARN deprecated @ksoft/api@3.1.9: KSoft is no longer active. Take a look at https://ravy.org/api
npm WARN tarball tarball data for prism-media@https://codeload.github.com/distubejs/prism-media/tar.gz/main#workaround.tar.gz (sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw==) seems to be corrupted. Trying again.
npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm WARN deprecated distube@3.3.4: Update to latest version instead
npm WARN deprecated discord-api-types@0.24.0: No longer supported. Install the latest release!
npm ERR! code EINTEGRITY
npm ERR! sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw== integrity checksum failed when using sha512: wanted sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw== but got sha512-NgqmmDCFM4cuPFRXBOcU9CYQ2ouYLivZ5OLMuM3lrNnaQ8mIiSfT8IuGqog9Oc1cPQll37l0o4ZJtys5zje9/Q==. (9969 bytes)

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-07-31T09_02_09_114Z-debug-0.log
install complete
```

**Comment by 0zunu** [comment]
> Can you please update the depencies and start using discord.js 14? 13 will be eol in a short time. I never saw such a big row of decrecated modules
> 
> ```
> Installing nodejs packages
> npm WARN tarball tarball data for prism-media@https://codeload.github.com/distubejs/prism-media/tar.gz/main#workaround.tar.gz (sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw==) seems to be corrupted. Trying again.
> npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
> npm WARN tarball tarball data for prism-media@https://codeload.github.com/distubejs/prism-media/tar.gz/main#workaround.tar.gz (sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw==) seems to be corrupted. Trying again.
> npm WARN deprecated @discordjs/builders@0.9.0: no longer supported
> npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
> npm WARN deprecated distube@3.3.4: Update to latest version instead
> npm WARN deprecated @ksoft/api@3.1.9: KSoft is no longer active. Take a look at https://ravy.org/api
> npm WARN deprecated @discordjs/builders@0.16.0: no longer supported
> npm WARN deprecated discord-api-types@0.24.0: No longer supported. Install the latest release!
> npm WARN deprecated @distube/youtube-dl@2.2.4: Use '@distube/yt-dlp' instead
> npm WARN deprecated @discordjs/collection@0.7.0: no longer supported
> npm ERR! code EINTEGRITY
> npm ERR! sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw== integrity checksum failed when using sha512: wanted sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw== but got sha512-NgqmmDCFM4cuPFRXBOcU9CYQ2ouYLivZ5OLMuM3lrNnaQ8mIiSfT8IuGqog9Oc1cPQll37l0o4ZJtys5zje9/Q==. (9969 bytes)
> 
> npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-07-31T09_02_03_131Z-debug-0.log
> npm WARN config production Use `--omit=dev` instead.
> npm WARN deprecated @distube/youtube-dl@2.2.4: Use '@distube/yt-dlp' instead
> npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
> npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> npm WARN deprecated @discordjs/collection@0.7.0: no longer supported
> npm WARN deprecated @discordjs/builders@0.9.0: no longer supported
> npm WARN tarball tarball data for prism-media@https://codeload.github.com/distubejs/prism-media/tar.gz/main#workaround.tar.gz (sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw==) seems to be corrupted. Trying again.
> npm WARN deprecated @discordjs/builders@0.16.0: no longer supported
> npm WARN deprecated @ksoft/api@3.1.9: KSoft is no longer active. Take a look at https://ravy.org/api
> npm WARN tarball tarball data for prism-media@https://codeload.github.com/distubejs/prism-media/tar.gz/main#workaround.tar.gz (sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw==) seems to be corrupted. Trying again.
> npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
> npm WARN deprecated distube@3.3.4: Update to latest version instead
> npm WARN deprecated discord-api-types@0.24.0: No longer supported. Install the latest release!
> npm ERR! code EINTEGRITY
> npm ERR! sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw== integrity checksum failed when using sha512: wanted sha512-2a/62b86i60OksrnliRwG7IGMHjFHM0KiRYk6YBi43IZpCZCf/ZLjXIbMGtzzeTZhEJy1Fi6Ke6kKtn2ObNjPw== but got sha512-NgqmmDCFM4cuPFRXBOcU9CYQ2ouYLivZ5OLMuM3lrNnaQ8mIiSfT8IuGqog9Oc1cPQll37l0o4ZJtys5zje9/Q==. (9969 bytes)
> 
> npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-07-31T09_02_09_114Z-debug-0.log
> install complete
> ```

soon
